POST http://localhost:8080/articles
Accept: application/json
Content-Type: application/json
Authorization: Basic YWRtaW46YWRtaW4=

{
  "title": "Podstawy Spring",
  "author": "Jan Kowalski",
  "category": "IT",
  "content": "..."
}

###

DELETE http://localhost:8080/articles/5bd208bb-e53f-4326-a987-3a71a5df1cba
Accept: application/json
Content-Type: application/json

###

PATCH http://localhost:8080/articles/88bcc10c-c001-45f8-8c63-b09b7c5d64de
Accept: application/json
Content-Type: application/json

{
  "title": "Podstawy Spring",
  "category": "IT",
  "content": "...",
  "tags": ["it", "java"]
}

###

PUT http://localhost:8080/articles/published/88bcc10c-c001-45f8-8c63-b09b7c5d64de
Accept: application/json
Content-Type: application/json

###

GET http://localhost:8080/articles/88bcc10c-c001-45f8-8c63-b09b7c5d64de
Accept: application/json
Content-Type: application/json
Authorization: Basic YWRtaW46YWRtaW4=

###

GET http://localhost:8080/categories/IT/articles?tag=it&tag=java
Accept: application/json
Content-Type: application/js

###

GET http://localhost:8080/users/me
Accept: application/json
Content-Type: application/json
Authorization: Basic YWRtaW46YWRtaW4=
