POST http://localhost:8080/articles
Accept: application/json
Content-Type: application/json
Authorization: Basic YWRtaW46YWRtaW4=

{
  "title": "Podstawy Spring",
  "author": "Jan Kowalski",
  "category": "IT",
  "content": "..."
}

###

DELETE http://localhost:8080/articles/d683e3a7-0ff5-495c-bb6c-d6a180ddd146
Accept: application/json
Content-Type: application/json

###

PATCH http://localhost:8080/articles/9c332296-d162-41cc-9156-be0b6fa8b68b
Accept: application/json
Content-Type: application/json

{
  "title": "Podstawy Spring",
  "category": "IT",
  "content": "...",
  "tags": ["it", "java"]
}

###

PUT http://localhost:8080/articles/published/09971197-a447-4795-8547-725c587e1c7e
Accept: application/json
Content-Type: application/json

###

GET http://localhost:8080/articles/09971197-a447-4795-8547-725c587e1c7e
Accept: application/json
Content-Type: application/json
#Authorization: Basic YWRtaW46MTIz
#Authorization: API_KEY 1234567890

###

GET http://localhost:8080/categories/IT/articles?tag=it&tag=java
Accept: application/json
Content-Type: application/js

###

GET http://localhost:8080/users/me
Accept: application/json
Content-Type: application/json
Authorization: Basic YWRtaW46YWRtaW4=
