POST http://localhost:8080/articles
Accept: application/json
Content-Type: application/json
Authorization: Basic amFuOjEyMw==

{
  "title": "Podstawy Spring",
  "author": "Jan Kowalski",
  "category": "IT",
  "content": "..."
}

###

DELETE http://localhost:8080/articles/f598102e-9b67-4417-9e97-5a6942a6fd28
Accept: application/json
Content-Type: application/json
Authorization: Basic amFuOjEyMw==

###

PATCH http://localhost:8080/articles/1c3674b8-5874-4c73-8003-9b887bbcc218
Accept: application/json
Content-Type: application/json
Authorization: Basic amFuOjEyMw==

{
  "title": "Podstawy Spring",
  "category": "IT",
  "content": "...",
  "tags": ["it", "java"]
}

###

PUT http://localhost:8080/articles/published/1c3674b8-5874-4c73-8003-9b887bbcc218
Accept: application/json
Content-Type: application/json
Authorization: Basic amFuOjEyMw==

###

GET http://localhost:8080/articles/1c3674b8-5874-4c73-8003-9b887bbcc218
Accept: application/json
Content-Type: application/json
#Authorization: Basic amFuOjEyMw==
Authorization: API_KEY 1234567890

###

GET http://localhost:8080/categories/IT/articles?tag=it&tag=java
Accept: application/json
Content-Type: application/js
Authorization: Basic amFuOjEyMw==

